language: ruby

before_install:
 - gem update --system 2.1.11
 - gem --version
 - sudo apt-get update -qq
 - sudo apt-get install libpcap-dev -qq
 - gem install bundler

env:
  global:
    - secure: "roJa3FuYA6gLdV0vtUe1GyuAU2WQ+E+jraT9QeKKHRQSU2TKYgeJ7MmxG3vSpIoZsHEdmrZh0UVTrMO436UHAG5V+qbSmP2gld0vSI2qDQ2dXbNoAIVUHex2oCDTa5OC0sJbz9W8Yrd0XoTY0O5gObPn6QfTzAHKgPz7ZC9bBwo="

script: "rake travis"

rvm:
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master
    - develop

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ca7b2e631cab5cddce0d
    on_success: always
    on_failure: always
    on_start: always
